vim.opt.autoindent = true -- Keep identation from previous line
vim.opt.breakindent = true -- Enable break indent
vim.opt.clipboard = 'unnamedplus' -- Sync with system clipboard
vim.opt.cursorline = true -- Enable highlighting of the current line
vim.opt.expandtab = true -- Use spaces instead of tabs
vim.opt.ignorecase = true -- Ignore case
vim.opt.list = true -- Show some invisible characters
vim.opt.listchars = { tab = '| ', trail = '·', nbsp = '␣' }
vim.opt.mouse = '' -- Enable mouse mode
vim.opt.number = true -- Print line number
vim.opt.relativenumber = true -- Relative line numbers
vim.opt.scrolloff = 10 -- Lines of context
vim.opt.shiftwidth = 2 -- Size of an indent
vim.opt.showmode = false -- Dont show mode since we have a statusline
vim.opt.signcolumn = 'yes'
vim.opt.smartcase = true -- Don't ignore case with capitals
vim.opt.smartindent = true
vim.opt.smarttab = true
vim.opt.softtabstop = 2 -- How many spaces are applied when pressing Tab
vim.opt.splitbelow = true -- Put new windows below current
vim.opt.splitright = true -- Put new windows right of current
vim.opt.swapfile = false -- Disable swapfile
vim.opt.tabstop = 2 -- Number of spaces tabs count for
vim.opt.undofile = true
vim.opt.undolevels = 10000
vim.opt.wrap = false
